#!/usr/bin/env python3
"""Regenerate tests/support/golden-v3-store.sql, the checked-in store every build must still replay.

Run this only when a deliberate format change makes the recorded history unreplayable, and say so in
the commit message: the point of the fixture is that an engine or diff change which breaks logs
already written fails CI instead of passing silently.
"""
import json
import os
import sqlite3
import tempfile
from pathlib import Path

from smoke_agent import ROOT, run_cli

OUTPUT = ROOT / 'tests/support/golden-v3-store.sql'


def record(database, directory):
    run_cli(database, 'import', ROOT / 'tests/support/execution-plan.json')
    plan = run_cli(database, 'export')
    keys = {w['key']: w for w in plan['work_items'].values()}
    keys['TEST-F']['title'] = 'Integration contract, clarified'
    added = json.loads(json.dumps(keys['TEST-F']))
    added.update(id='00000000-0000-4000-8000-00000000f00d', key='TEST-G')
    added['execution']['status'] = 'Proposed'
    plan['work_items'][added['id']] = added
    plan['dependencies'][0]['lag_hours'] = 1.929842284342272e-18
    candidate = directory / 'candidate.json'
    candidate.write_text(json.dumps(plan))
    run_cli(database, 'plan', 'apply', candidate, '--reason', 'Clarify scope', '--actor', 'human:lead')
    run_cli(database, 'ratify', 'TEST-G', '--actor', 'human:lead')
    run_cli(database, 'decide', 'TEST-GATE', 'proceed', '--actor', 'human:lead')
    for arguments in [('claim', 'TEST-A'), ('start', 'TEST-A'), ('progress', 'TEST-A', '50'),
                      ('block', 'TEST-A', 'waiting for a fixture'), ('unblock', 'TEST-A'),
                      ('submit', 'TEST-A', '--note', 'acceptance run attached')]:
        run_cli(database, *arguments, '--actor', 'agent:worker')
    run_cli(database, 'verify', 'TEST-A', '--actor', 'human:reviewer')


def dump(database):
    with sqlite3.connect(database) as connection:
        version = connection.execute('PRAGMA user_version').fetchone()[0]
        lines = list(connection.iterdump())
    header = ['-- Generated by scripts/golden_store.py; regenerate only for a deliberate format change.']
    return '\n'.join([*header, *lines, f'PRAGMA user_version = {version};', ''])


if __name__ == '__main__':
    with tempfile.TemporaryDirectory(prefix='dpm-golden-') as temporary:
        directory = Path(temporary)
        os.environ['DPM_CONFIG_DIR'] = str(directory / 'config')
        database = directory / 'golden.sqlite'
        record(database, directory)
        run_cli(database, 'verify-store')
        OUTPUT.write_text(dump(database))
    print(f'wrote {OUTPUT.relative_to(ROOT)}')
